export const types = {
  ADD_TASK: "ADD_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  FETCH_TASKS: "FETCH_TASKS",
  FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
  FETCH_TASKS_FAILED: "FETCH_TASKS_FAILED",
  CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
  CREATE_TASK_FAILED: "CREATE_TASK_FAILED",
  UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
  UPDATE_TASK_FAILED: "UPDATE_TASK_FAILED",
};